modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="sf2sf"
version="1.0.0"
displayName="SF2SF"
description="Adds a kick attack on L key"

[[dependencies.sf2sf]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sf2sf]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
